const  mongoose = require('mongoose');

const Schema = mongoose.Schema;

const Invoice = new Schema({
  SNID: { type: String },
  BNID: { type: String },
  STIN: { type: String },
  SRN: { type: String },
  SSSTN: { type: String },
  STTRN: { type: String },
  SE: { type: String },
  SMC: { type: String },
  SBA: { type: String },
  BT: { type: String },
  BSRN: { type: String },
  BRN: { type: String },
  BSSTN: { type: String },
  BE: { type: String },
  SA: { type: String },
  BA: { type: String },
  SCN: { type: String },
  BCN: { type: String },
  EIV: { type: String },
  EIT: { type: String },
  EIC: { type: String },
  OEIRN: { type: String },
  EIDAT: { type: String },
  DATOV: { type: String },
  IDS: { type: String },
  ICC: { type: String },
  CER: { type: String },
  FOB: { type: String },
  BP: { type: String },
  IRBMUN: { type: String },
  CFI: { type: String },
  DOPOS: { type: String },
  UP: { type: String },
  QUAN: { type: String },
  MSR: { type: String },
  DR: { type: String },
  DA: { type: String },
  DOTE: { type: String },
  AEFT: { type: String },
  SBT: { type: String },
  TET: { type: String },
  TIT: { type: String },
  TT: { type: String },
  TR: { type: String },
  TA: { type: String },
  PM: { type: String },
  SBAN: { type: String },
  PT: { type: String },
  PA: { type: String },
  PD: { type: String },
  PRN: { type: String },
});

module.exports = mongoose.model("Invoice", Invoice);
